[package]
name = "mfj"
version = "0.1.0"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["release_max_level_warn"] }
simple_logger = { version = "1.3.0", default-features = false }
reqwest = "0.9.24"
clap = "2.33.0"
