[package]
name = "mfj"
version = "1.0.1"
authors = ["Lauri Gustafsson <me@gustafla.space>"]
edition = "2018"

[features]
default = ["dotenv"]

[dependencies]
log = "0.4"
simple_logger = { version = "1.3.0", default-features = false }
reqwest = "0.9.24"
clap = "2.33.0"
lazy_static = "1"
dotenv = { version = "0.15.0", optional = true }
humantime = "1.3.0"
chrono = "0.4.10"
serde_json = "1.0.44"
serde = "1.0.104"
ctrlc = "3.1.3"
flate2 = "1.0.13"
